default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] ||  60 %>
  port: 5432
  host: localhost
  username: postgres_ebay_user
  password: VKtM9ldvwJePAZftWHVp20BqTb9IuIpg

development:
  <<: *default
  database: EBAY_development

test:
  <<: *default
  database: EBAY_test

production:
  <<: *default
  database: postgres://postgres_ebay_user:VKtM9ldvwJePAZftWHVp20BqTb9IuIpg@dpg-ciqer05gkuvrtobmph5g-a/postgres_ebay
  username: postgres_ebay_user
  password: VKtM9ldvwJePAZftWHVp20BqTb9IuIpg

