default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] ||  60 %>
  port: 5432
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: EBAY_development

test:
  <<: *default
  database: EBAY_test

production:
  <<: *default
  database: EBAY_production
  username: postgres
  password: postgres

